package com.example.mykind.fir

import org.jetbrains.kotlin.builtins.functions.FunctionTypeKind
import org.jetbrains.kotlin.config.LanguageVersion
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * Names and identifiers used by the @MyKind function-type family.
 *
 * The synthetic function classes generated by the FIR resolver live in the
 * `com.example.mykind.synthetic` package and are named `MyKindFunctionN` /
 * `KMyKindFunctionN`. The IR transformer rewrites them back to the built-in
 * `kotlin.FunctionN` so the JVM backend can emit valid bytecode.
 */
object MyKindNames {
    val ANNOTATION_FQN: FqName = FqName("com.example.MyKind")
    val ANNOTATION_CLASS_ID: ClassId = ClassId.topLevel(ANNOTATION_FQN)

    val SYNTHETIC_PACKAGE: FqName = FqName("com.example.mykind.synthetic")

    const val NON_REFLECT_PREFIX: String = "MyKindFunction"
    const val REFLECT_PREFIX: String = "KMyKindFunction"

    val FULL_NON_REFLECT_PREFIX: String =
        SYNTHETIC_PACKAGE.child(Name.identifier(NON_REFLECT_PREFIX)).asString()
    val FULL_REFLECT_PREFIX: String =
        SYNTHETIC_PACKAGE.child(Name.identifier(REFLECT_PREFIX)).asString()
}

/** Non-reflect kind: the actual lambda type written as `@MyKind () -> Unit`. */
object MyKind : FunctionTypeKind(
    packageFqName = MyKindNames.SYNTHETIC_PACKAGE,
    classNamePrefix = MyKindNames.NON_REFLECT_PREFIX,
    annotationOnInvokeClassId = MyKindNames.ANNOTATION_CLASS_ID,
    isReflectType = false,
    isInlineable = false,
) {
    override val prefixForTypeRender: String get() = "@MyKind"

    override val serializeAsFunctionWithAnnotationUntil: String
        get() = LanguageVersion.KOTLIN_2_1.versionString

    override fun reflectKind(): FunctionTypeKind = KMyKind
}

/** Reflect counterpart: `KMyKindFunctionN`, used for `KFunctionN`-style references. */
object KMyKind : FunctionTypeKind(
    packageFqName = MyKindNames.SYNTHETIC_PACKAGE,
    classNamePrefix = MyKindNames.REFLECT_PREFIX,
    annotationOnInvokeClassId = MyKindNames.ANNOTATION_CLASS_ID,
    isReflectType = true,
    isInlineable = false,
) {
    override val serializeAsFunctionWithAnnotationUntil: String
        get() = LanguageVersion.KOTLIN_2_1.versionString

    override fun nonReflectKind(): FunctionTypeKind = MyKind
}
